### ISSUE TITLE
Completely offline training

### ISSUE THREAD

**Issue by nk-dev0** [developmentseed/skynet-data#3]
Thank you for this code, it looks to be very useful. I want to try this out on some images I have already downloaded, and using a completely offline process (which includes already having downloaded the entire planet's OSM QA tiles). How might one go about this?

**Comment by anandthakker** [comment]
The scripts here are just for preparing data -- once you've run them, you should have a directory full of data that is ready to be trained completely offline.

Does this answer your question?

**Comment by nk-dev0** [comment]
I suppose I should reframe my question: is it possible to just create the OSM masks based on image files I already have, instead of querying a server to get certain image files?
